# buildconfig-producer.yaml

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  output:
    to:
      kind: ImageStreamTag
      name: kafka-producer:latest
  source:
    type: Git
    git:
      uri: https://github.com/tigeryi1998/kafka-k8s
    contextDir: kafka-producer/
    sourceSecret:
      name: ds551 # Replace with your actual secret name if needed
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: kafka-producer-github-webhook-secret
    - type: Generic
      generic:
        secretReference:
          name: kafka-producer-generic-webhook-secret
  runPolicy: Serial
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
