# producer-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-eda-producer
  labels:
    app: spark-eda-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-eda-producer
  template:
    metadata:
      labels:
        app: spark-eda-producer
    spec:
      containers:
        - name: spark-eda-producer
          image: image-registry.openshift-image-registry.svc:5000/ds551-2025fall-cb9303/spark-eda-producer:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: KAFKA_TOPIC
              value: covid_data
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      restartPolicy: Always
